version: '2'

services:

  emupay:
    image: 'jadajin/emupay:latest'
    ports:
      - "8100:8100"
    restart: always

  emupay_android:
    command: ionic serve --port 2333 &
    image: 'jadajin/emupay_android:release'
    privileged: true
    ports:
      - "2333:2333"
      - "8100:8100"
      - "8101:8101"
    restart: always
